# Generated by Django 2.2.6 on 2019-10-27 14:59

from django.db import migrations, models
import django.utils.crypto
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('streamy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stream',
            old_name='started_at',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='stream',
            name='name',
            field=models.CharField(default=functools.partial(django.utils.crypto.get_random_string, *(8,), **{}), max_length=8, unique=True),
        ),
    ]
