# Generated by Django 2.2.6 on 2019-11-09 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamy', '0002_auto_20191027_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='privacy',
            field=models.CharField(choices=[('public', 'Public'), ('unlisted', 'Unlisted')], default='public', max_length=12),
        ),
    ]
