# Generated by Django 2.2.6 on 2019-11-10 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamy', '0003_stream_privacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='stream',
            name='title',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
