# Generated by Django 2.2.6 on 2019-11-10 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamy', '0004_auto_20191110_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='title',
            field=models.CharField(max_length=128),
        ),
    ]
