# Generated by Django 2.2.6 on 2019-11-17 20:58

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streamy', '0005_auto_20191110_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', django.contrib.postgres.fields.jsonb.JSONField()),
                ('video', django.contrib.postgres.fields.jsonb.JSONField()),
                ('stream', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='streamy.Stream')),
            ],
        ),
    ]
