# Generated by Django 2.2.6 on 2019-11-20 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamy', '0006_streammeta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='privacy',
            field=models.CharField(choices=[('public', 'Public'), ('unlisted', 'Unlisted'), ('link', 'Link')], default='public', max_length=12),
        ),
    ]
