version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8000:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
      - static_files:/static:ro
    restart: unless-stopped

  nginx-flv:
    build:
      context: ./nginx-flv
    image: streamy/nginx-flv
    expose:
      - "8000"
    ports:
      - "1935:1935"
    restart: unless-stopped

  backend:
    build:
      context: ./app
    image: streamy/backend
    env_file:
      - django.env
    environment:
      - DJANGO_SETTINGS_MODULE=config.docker_settings
    expose:
      - "8000"
    volumes:
      - static_files:/static
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: unless-stopped

volumes:
  postgres_data:
  static_files:
