version: '2'
services:
  nginx:
    build: nginx
    volumes:
      - static_files:/static:ro
      - video_thumbnails:/thumbs:ro

  nginx-flv:
    build: nginx-flv
    expose:
      - "8000"
    ports:
      - "1935:1935"
    volumes:
      - video_thumbnails:/thumbs

  backend:
    build: app
    env_file:
      - django.env
    environment:
      - DJANGO_SETTINGS_MODULE=config.docker_settings
    expose:
      - "8000"
    volumes:
      - static_files:/static
    depends_on:
      - db

  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  fix-thumbnail-permissions:
    image: nginx:stable-alpine
    volumes:
      - video_thumbnails:/thumbs
    command: chmod -R 777 /thumbs

volumes:
  postgres_data:
  static_files:
  video_thumbnails:
